/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import utils.UserProfile;
import utils.DatePicker;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author prath
 */
public class PersonalDetails extends javax.swing.JFrame {
    
    private UserProfile userProfile;
    private Image image;
    private BufferedImage bufferedImage;
  
    /**
     * Creates new form NewJFrame
     * @param userProfile
     */
    public PersonalDetails(UserProfile userProfile) {
        initComponents();
        userProfile = new UserProfile();
        this.userProfile = userProfile;
        mainFrame.setAlignmentX(Component.CENTER_ALIGNMENT);
        mainFrame.setPreferredSize(new Dimension(400, 100));
        mainFrame.setMaximumSize(new Dimension(400, 100));
        
        // Catching both NPE and IOExceptions. Not using the generic Exception. (   Clean & Optimized coding :))))  )
        try {
                // Loading the static asset from the drawables folder
                bufferedImage = ImageIO.read(new File("src\\assets\\user_icon.png"));
                image = bufferedImage.getScaledInstance(profilePhotoIcon.getWidth(), profilePhotoIcon.getHeight(),
                    Image.SCALE_SMOOTH);
                profilePhotoIcon.setIcon(new ImageIcon(image));
            } catch(NullPointerException | IOException ep) {     
            }
    }
    
    public PersonalDetails() {
        initComponents();
        userProfile = new UserProfile();
        this.userProfile = userProfile;
        
        // Catching both NPE and IOExceptions. Not using the generic Exception. (   Clean & Optimized coding :))))  )
        try {
                // Loading the static asset from the drawables folder
                bufferedImage = ImageIO.read(new File("src\\assets\\user_icon.png"));
                image = bufferedImage.getScaledInstance(profilePhotoIcon.getWidth(), profilePhotoIcon.getHeight(),
                    Image.SCALE_SMOOTH);
                profilePhotoIcon.setIcon(new ImageIcon(image));
              } catch(NullPointerException | IOException ep) {     
              }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainFrame = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        labelPersonalDetails = new javax.swing.JLabel();
        labelFirstName = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        labelContact = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        firstNameInput = new javax.swing.JTextField();
        lastNameInput = new javax.swing.JTextField();
        contactNumberInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        addressInput = new javax.swing.JTextField();
        labelChooseFile = new javax.swing.JLabel();
        chooseFile = new javax.swing.JButton();
        labelDob = new javax.swing.JLabel();
        datePicker = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        profilePhotoIcon = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        mainFrame.setForeground(new java.awt.Color(204, 255, 255));

        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));

        labelPersonalDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPersonalDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPersonalDetails.setText("Enter Your Personal Details");

        labelFirstName.setText("First Name");

        labelLastName.setText("Last Name");

        labelContact.setText("Phone No.");

        labelEmail.setText("Email-ID");

        labelAddress.setText("Address");

        firstNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameInputActionPerformed(evt);
            }
        });

        lastNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameInputActionPerformed(evt);
            }
        });

        contactNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberInputActionPerformed(evt);
            }
        });

        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });

        addressInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressInputActionPerformed(evt);
            }
        });

        labelChooseFile.setText("Choose a profile picture");

        chooseFile.setText("Choose File");
        chooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileActionPerformed(evt);
            }
        });

        labelDob.setText("Date of Birth");

        datePicker.setText("Pick a Date");
        datePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datePickerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelPersonalDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEmail)
                            .addComponent(labelLastName)
                            .addComponent(labelFirstName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(labelContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(labelChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDob, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(datePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPersonalDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFirstName)
                    .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLastName)
                    .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContact)
                    .addComponent(contactNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmail)
                    .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAddress)
                    .addComponent(addressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDob)
                    .addComponent(datePicker))
                .addGap(22, 22, 22)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseFile))
                .addGap(64, 64, 64))
        );

        nextButton.setText("Next");
        nextButton.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 102, 102)));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        profilePhotoIcon.setBackground(new java.awt.Color(0, 0, 0));
        profilePhotoIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profilePhotoIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame);
        mainFrame.setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainFrameLayout.createSequentialGroup()
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(profilePhotoIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
            .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainFrameLayout.createSequentialGroup()
                    .addContainerGap(21, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(110, Short.MAX_VALUE)))
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profilePhotoIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(348, 348, 348)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainFrameLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        storeFields();
        validateFields();
    }//GEN-LAST:event_nextButtonActionPerformed
    
    private void storeFields() {
        // Using the setters in the UserProfile class to store inputs in memory
        userProfile.setFirstName(firstNameInput.getText());
        userProfile.setLastName(lastNameInput.getText());
        userProfile.setEmailAddress(emailInput.getText());
        userProfile.setPersonAddress(addressInput.getText());
        userProfile.setPersonNumber(contactNumberInput.getText());
        userProfile.setAge(datePicker.getText());
    }
    
    private void validateFields() {
        // Validations for grabbing the correct inputs from the user
        if (!userProfile.validateName(firstNameInput.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter a valid name.");
            return;
        }
        if(!userProfile.validateName(lastNameInput.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter a valid surname.");
            return;
        }
        if (!userProfile.validatePhone(contactNumberInput.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter a valid contact.");
            return;
        }
        if(!userProfile.validateEmail(emailInput.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Email-ID.");
            return;
        }
        if(!userProfile.validateDate(datePicker.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter a valid date.");
            return;
        }
        if(userProfile.getPhotoPath() == null) {
            JOptionPane.showMessageDialog(this, "Please select a profile photo first.");
            return;
        }
        openNextPanel();
    }
    
    private void datePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datePickerActionPerformed
        pickDate();
    }//GEN-LAST:event_datePickerActionPerformed

    private void pickDate() {
        // Add a date picker for picking a date. Not that great but works.
        JButton pickButton = new JButton("Pick a date");
        // Also give an option for manually entering a date
        JButton submitDate = new JButton("Submit date manually");
        final JFormattedTextField dateInput = new JFormattedTextField();
        JLabel labelDate = new JLabel(" or write date manually ", JLabel.CENTER);
        JLabel labelFormat = new JLabel(" DD / MM / YYYY ", JLabel.CENTER);
        try {
            // Set a pre defined format for setting the date
            dateInput.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("HH-HH-HHHH")));
        } catch (ParseException ex) {
            Logger.getLogger(PersonalDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        JPanel backgroundPanel = new JPanel();
        backgroundPanel.add(pickButton);
        backgroundPanel.add(labelDate);
        backgroundPanel.add(dateInput);
        backgroundPanel.add(labelFormat);
        backgroundPanel.add(submitDate);
        final JFrame backgroundFrame = new JFrame();
        backgroundFrame.getContentPane().add(backgroundPanel);
        backgroundFrame.pack();
        backgroundFrame.setVisible(true);
        submitDate.addActionListener((var ae) -> {
            if (!userProfile.validateDate(dateInput.getText())) {
                backgroundFrame.setVisible(false);
                // Use a validator for checking the date
                JOptionPane.showMessageDialog(this, "Please enter a valid date.");
                return;
            }
            userProfile.setDob(dateInput.getText());
            datePicker.setText(dateInput.getText());
            backgroundPanel.setVisible(false);
            backgroundFrame.setVisible(false);
        });
        pickButton.addActionListener((var ae) -> {
            datePicker.setText(new DatePicker(backgroundFrame).setPickedDate());
            backgroundFrame.setVisible(false);
            backgroundPanel.setVisible(false);
        });
    }
    
    private void chooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileActionPerformed
        // Add filter for selecting only images
        FileFilter filterImages = new FileNameExtensionFilter("images","jpeg", "png", "jpg");
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(filterImages);
        int open = fileChooser.showOpenDialog(this);

        if (open == javax.swing.JFileChooser.APPROVE_OPTION){

            // Get the path of the selected file
            File path = fileChooser.getSelectedFile();

            // Convert the path to string
            String file_name = path.toString();
            
            // Save it as a variable for calling it later while displaying user profile photo
            userProfile.setPhotoPath(file_name);

            // Set the button's name as the file path
            chooseFile.setText(file_name);
        }
    }//GEN-LAST:event_chooseFileActionPerformed

    private void addressInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressInputActionPerformed
    }//GEN-LAST:event_addressInputActionPerformed

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
    }//GEN-LAST:event_emailInputActionPerformed

    private void contactNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberInputActionPerformed
    }//GEN-LAST:event_contactNumberInputActionPerformed

    private void lastNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameInputActionPerformed
    }//GEN-LAST:event_lastNameInputActionPerformed

    private void firstNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameInputActionPerformed

    }//GEN-LAST:event_firstNameInputActionPerformed

    private void openNextPanel() {
        // Pass the instance of userprofile for keeping the details in the local machine's memory
        JOptionPane.showMessageDialog(this, "Saved succesfully!");
        SecurityDetails sd = new SecurityDetails(userProfile);
        new SecurityDetails(userProfile).setVisible(true);
        // Close this window and open a new one. Also release the thread for mem optimizations.
        super.dispose();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and diuserProfilelay the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressInput;
    private javax.swing.JButton chooseFile;
    private javax.swing.JTextField contactNumberInput;
    private javax.swing.JButton datePicker;
    private javax.swing.JTextField emailInput;
    private javax.swing.JTextField firstNameInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelChooseFile;
    private javax.swing.JLabel labelContact;
    private javax.swing.JLabel labelDob;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelPersonalDetails;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JPanel mainFrame;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel profilePhotoIcon;
    // End of variables declaration//GEN-END:variables
}
