/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utils.UserProfile;

/**
 *
 * @author prath
 */
public class SocialDetails extends javax.swing.JFrame {
    
    private UserProfile userProfile;
    private Image image;
    private BufferedImage bufferedImage;

    /**
     * Creates new form SocialDetails
     */
    public SocialDetails(UserProfile userProfile) {
        this.userProfile = userProfile;
        initComponents();
        
        // Catching both NPE and IOExceptions. Not using the generic Exception. (   Clean & Optimized coding :))))  )
        try {
                // Loading the static asset from the drawables folder
                bufferedImage = ImageIO.read(new File("src\\assets\\social.jpg"));
                image = bufferedImage.getScaledInstance(socialIcon.getWidth(), socialIcon.getHeight(),
                    Image.SCALE_SMOOTH);
                socialIcon.setIcon(new ImageIcon(image));
            } catch(NullPointerException | IOException ep) {     
            }
    }
    
    /**
     * Constructor for running the frame stand alone without creating instance of UserProfile
     */
    public SocialDetails() {
        this.userProfile = userProfile;
        initComponents();
        
        // Catching both NPE and IOExceptions. Not using the generic Exception. (   Clean & Optimized coding :))))  )
        try {
                // Loading the static asset from the drawables folder
                bufferedImage = ImageIO.read(new File("src\\assets\\social.jpg"));
                image = bufferedImage.getScaledInstance(socialIcon.getWidth(), socialIcon.getHeight(),
                    Image.SCALE_SMOOTH);
                socialIcon.setIcon(new ImageIcon(image));
            } catch(NullPointerException | IOException ep) {     
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelSocialMedia = new javax.swing.JLabel();
        inputLinkedIN = new javax.swing.JTextField();
        labelLinkedIn = new javax.swing.JLabel();
        labelIp = new javax.swing.JLabel();
        inputIP = new javax.swing.JTextField();
        nextButto = new javax.swing.JButton();
        socialIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        labelSocialMedia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelSocialMedia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSocialMedia.setText("Enter Your Social Media Details");

        inputLinkedIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLinkedINActionPerformed(evt);
            }
        });

        labelLinkedIn.setText("LinkedIN Username");

        labelIp.setText("IP Address");

        inputIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIPActionPerformed(evt);
            }
        });

        nextButto.setText("Next");
        nextButto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4));
        nextButto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtoActionPerformed(evt);
            }
        });

        socialIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        socialIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLinkedIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelIp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(55, 55, 55)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputLinkedIN, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(inputIP))
                        .addGap(63, 63, 63))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(socialIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(labelSocialMedia, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelSocialMedia)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelLinkedIn))
                    .addComponent(inputLinkedIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelIp))
                    .addComponent(inputIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(socialIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputLinkedINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLinkedINActionPerformed

    }//GEN-LAST:event_inputLinkedINActionPerformed

    private void inputIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIPActionPerformed

    private void nextButtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtoActionPerformed
        storeFields();
        validateFields();
    }//GEN-LAST:event_nextButtoActionPerformed
 
    private void storeFields() {
        // Store the data inputs in memory
        userProfile.setLinkedinUrl(inputLinkedIN.getText());
        userProfile.setIpAddress(inputIP.getText());
    }
    
    private void openNextPanel() {
        JOptionPane.showMessageDialog(this, "Saved succesfully!");
        ViewProfile viewProfile = new ViewProfile(userProfile);
        viewProfile.setVisible(true);
        super.dispose();
    }
    
    private void validateFields() {
        // Validate the IP
        System.out.println(userProfile.getLinkedInUsername());
        if (userProfile.getLinkedInUsername().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter your LinkedIN username.");
            return;
        }
        if (!userProfile.validateIp(inputIP.getText()) || userProfile.getIpAddress().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter a valid IP.");
            return;
        }
        openNextPanel();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SocialDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SocialDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SocialDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SocialDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and diuserProfilelay the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SocialDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputIP;
    private javax.swing.JTextField inputLinkedIN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelIp;
    private javax.swing.JLabel labelLinkedIn;
    private javax.swing.JLabel labelSocialMedia;
    private javax.swing.JButton nextButto;
    private javax.swing.JLabel socialIcon;
    // End of variables declaration//GEN-END:variables
}
