/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import utils.UserProfile;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.util.Locale;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author prath
 */
public class ViewProfile extends javax.swing.JFrame {
    
    private UserProfile userProfile;
    private Image dimg;
    private BufferedImage bufferedImage;
    private String capitalizedName;
    private String capitalizedSurname;
    public static String DATE_FORMAT_INPUT = "ddMMyyyy";
    /**
     * Creates new form ViewProfile
     */
    public ViewProfile(UserProfile userProfile) {
        this.userProfile = userProfile;
        initComponents();
        displayElements();
    }

    public ViewProfile() {
        this.userProfile = userProfile;
        initComponents();
        displayElements();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        profileHeader = new javax.swing.JLabel();
        profilePhoto = new javax.swing.JButton();
        userName = new javax.swing.JLabel();
        userSurname = new javax.swing.JLabel();
        userContact = new javax.swing.JLabel();
        userEmail = new javax.swing.JLabel();
        userAddress = new javax.swing.JLabel();
        socialDetailsLabel = new javax.swing.JLabel();
        linkedIN = new javax.swing.JButton();
        ipAddress = new javax.swing.JButton();
        personalDetailsLabel = new javax.swing.JLabel();
        socialDetailsLabel1 = new javax.swing.JLabel();
        ssnLabel = new javax.swing.JLabel();
        medicalNumber = new javax.swing.JLabel();
        healthPlanNumber = new javax.swing.JLabel();
        bankNumber = new javax.swing.JLabel();
        licenceNumber = new javax.swing.JLabel();
        vehicleNumber = new javax.swing.JLabel();
        deviceIdentifiers = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        faxNumber = new javax.swing.JLabel();
        userAge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        profileHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        profileHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileHeader.setText("Profile");

        profilePhoto.setText("User Photo");
        profilePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePhotoActionPerformed(evt);
            }
        });

        userName.setText("User Name");

        userSurname.setText("User surname");

        userContact.setText("User Contact");

        userEmail.setText("User Email");

        userAddress.setText("User Address");

        socialDetailsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        socialDetailsLabel.setText("  Social Details");
        socialDetailsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        linkedIN.setText("LinkedIN Profile");
        linkedIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkedINActionPerformed(evt);
            }
        });

        ipAddress.setText("IP Address");

        personalDetailsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        personalDetailsLabel.setText("Personal Details");
        personalDetailsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        socialDetailsLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        socialDetailsLabel1.setText("Social Details");
        socialDetailsLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ssnLabel.setText("SSN");

        medicalNumber.setText("Medical Number");

        healthPlanNumber.setText("Health Plan Number ");

        bankNumber.setText("Bank Account Number");

        licenceNumber.setText("License Number");

        vehicleNumber.setText("Vehicle Number");

        deviceIdentifiers.setText("Device Identifiers");

        exitButton.setText("Go back to main screen");
        exitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        faxNumber.setText("Fax Number");

        userAge.setText("User Age");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(profileHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(profilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userContact, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(personalDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(socialDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(linkedIN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ipAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(49, 49, 49))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(userAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(userAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(socialDetailsLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ssnLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicalNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(healthPlanNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenceNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deviceIdentifiers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(faxNumber)
                        .addGap(145, 145, 145)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(personalDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(socialDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(linkedIN)
                                .addGap(32, 32, 32)
                                .addComponent(ipAddress)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(socialDetailsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ssnLabel)
                        .addGap(18, 18, 18)
                        .addComponent(medicalNumber)
                        .addGap(21, 21, 21)
                        .addComponent(healthPlanNumber)
                        .addGap(22, 22, 22)
                        .addComponent(bankNumber)
                        .addGap(18, 18, 18)
                        .addComponent(licenceNumber)
                        .addGap(18, 18, 18)
                        .addComponent(vehicleNumber)
                        .addGap(18, 18, 18)
                        .addComponent(deviceIdentifiers)
                        .addGap(18, 18, 18)
                        .addComponent(faxNumber)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profilePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePhotoActionPerformed
        JOptionPane.showMessageDialog(this, "Hi " + userProfile.getFirstName() + "!!");
    }//GEN-LAST:event_profilePhotoActionPerformed

    private void linkedINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkedINActionPerformed
        try {
            // Grab the stored linkedin url from the memory
            String linkedInUrl = userProfile.getLinkedinUrl();
            // Consructing the desktop class for opening a new window (Browser Intent)
            Desktop browserIntent = Desktop.getDesktop();
            URI uriLinkedin = new URI(linkedInUrl);
            browserIntent.browse(uriLinkedin.resolve(uriLinkedin));
            } catch (URISyntaxException| IOException ex) {
        }
    }//GEN-LAST:event_linkedINActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        WelcomeFrame welcomeFrame = new WelcomeFrame(userProfile, false);
        welcomeFrame.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and diuserProfilelay the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProfile().setVisible(true);
            }
        });
    }
    
    private void displayElements() {
        // Capitalize the first letter of names
        capitalizedName = userProfile.getFirstName().substring(0,1).toUpperCase() + userProfile.getFirstName().substring(1).toLowerCase();
        capitalizedSurname = userProfile.getLastName().substring(0,1).toUpperCase() + userProfile.getLastName().substring(1).toLowerCase();
        // Display all the stored variables as UI elements
        profileHeader.setText(capitalizedName + "'s" + " Profile");
        userName.setText("Name: " + capitalizedName);
        userSurname.setText("Surname: " + capitalizedSurname);
        userEmail.setText("Email-ID: " + userProfile.getEmailAddress());
        userContact.setText("Contact: " + String.valueOf(userProfile.getPersonNumber()));
        userAddress.setText("Address: " + userProfile.getPersonAddress());
        ipAddress.setText("IP: " + String.valueOf(userProfile.getIpAddress()));
        ssnLabel.setText("SSN: " + String.valueOf(userProfile.getSsnUser()));
        medicalNumber.setText("Medical Number: " + String.valueOf(userProfile.getMedicalNumber()));
        healthPlanNumber.setText("Health Plan No: " + String.valueOf(userProfile.getHealthPlanNumber()));
        bankNumber.setText("Bank Account No: " + String.valueOf(userProfile.getBankAccountNumber()));
        licenceNumber.setText("License No: " + String.valueOf(userProfile.getLicenseNumber()));
        vehicleNumber.setText("Vehicle No: " + String.valueOf(userProfile.getVehicleNumber()));
        deviceIdentifiers.setText("Device Identifiers: " + String.valueOf(userProfile.getDeviceIdentifiers()));
        faxNumber.setText("Fax No: " + String.valueOf(userProfile.getPersonFaxNumber()));
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        LocalDate date = LocalDate.parse(userProfile.getAge(), formatter);
        userAge.setText("Age: " + calculateAge(date, LocalDate.now()));
        
        
        
        // UserProfile photo
        try {
              bufferedImage = ImageIO.read(new File(userProfile.getPhotoPath())); // path is your file or image path
              dimg = bufferedImage.getScaledInstance(profilePhoto.getWidth(), profilePhoto.getHeight(),
                Image.SCALE_SMOOTH);
            // profilePhoto.setText(file_name);
            profilePhoto.setIcon(new ImageIcon(dimg));
              // chooseFile.setIcon( new ImageIcon(bufferedImage));
              } catch(NullPointerException | IOException ep) {     
              }
    }
    
    // Calculate Age from date of birth
    public static int calculateAge(LocalDate birthDate, LocalDate currentDate) {
        if ((birthDate != null) && (currentDate != null)) {
            return Period.between(birthDate, currentDate).getYears();
        } else {
            return 0;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bankNumber;
    private javax.swing.JLabel deviceIdentifiers;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel faxNumber;
    private javax.swing.JLabel healthPlanNumber;
    private javax.swing.JButton ipAddress;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel licenceNumber;
    private javax.swing.JButton linkedIN;
    private javax.swing.JLabel medicalNumber;
    private javax.swing.JLabel personalDetailsLabel;
    private javax.swing.JLabel profileHeader;
    private javax.swing.JButton profilePhoto;
    private javax.swing.JLabel socialDetailsLabel;
    private javax.swing.JLabel socialDetailsLabel1;
    private javax.swing.JLabel ssnLabel;
    private javax.swing.JLabel userAddress;
    private javax.swing.JLabel userAge;
    private javax.swing.JLabel userContact;
    private javax.swing.JLabel userEmail;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userSurname;
    private javax.swing.JLabel vehicleNumber;
    // End of variables declaration//GEN-END:variables
}
